### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by d0ubl3puls4r** [rdkr/oniongen-go#4]
root@kali:~/oniongen-go# go run main.go "^TEST" 5
main.go:14:2: cannot find package "golang.org/x/crypto/ed25519" in any of:
	/usr/lib/go-1.14/src/golang.org/x/crypto/ed25519 (from $GOROOT)
	/root/go/src/golang.org/x/crypto/ed25519 (from $GOPATH)
main.go:15:2: cannot find package "golang.org/x/crypto/sha3" in any of:
	/usr/lib/go-1.14/src/golang.org/x/crypto/sha3 (from $GOROOT)
	/root/go/src/golang.org/x/crypto/sha3 (from $GOPATH)

Obs: I have GO installed on my system using the command "apt install golang"

how to solve this problem?
Thank you

**Comment by rdkr** [comment]
hey @d0ubl3puls4r, it looks like the imports broke since i wrote this. i have just updated them if you'd like to try again.

**Comment by bombardinotungtung** [comment]
go 14.4 issue persists

**Comment by rdkr** [comment]
hi @d0ubl3puls4r @doggukan, i cannot reproduce any issue with imports on mac or in docker.

dockerfile:
```
FROM golang:1.14.4
WORKDIR /go/src/oniongen-go
ADD . .
RUN go build
CMD ["./oniongen-go", "^TES", "5"]
```

build and run:
```
15:28:24 in oniongen-go on  master [?] ➜ docker build -t oniongen-go .
Sending build context to Docker daemon  48.13kB
Step 1/5 : FROM golang:1.14.4
 ---> 05feda542433
Step 2/5 : WORKDIR /go/src/oniongen-go
 ---> Using cache
 ---> a1b85b9de2b2
Step 3/5 : ADD . .
 ---> 297140344b02
Step 4/5 : RUN go build
 ---> Running in 7a07a30d6aa6
go: downloading golang.org/x/crypto v0.0.0-20200414173820-0848c9571904
Removing intermediate container 7a07a30d6aa6
 ---> 4fb2f0a64416
Step 5/5 : CMD ["./oniongen-go", "^TES", "5"]
 ---> Running in 663959ea6a14
Removing intermediate container 663959ea6a14
 ---> 51db58d843d1
Successfully built 51db58d843d1
Successfully tagged oniongen-go:latest
15:28:45 in oniongen-go on  master [?] ➜ docker run oniongen-go       
testi4k6nxzl5nyusvefzxavkneia2y5ajwl2wxwoutvru2sbio6uzqd.onion
tescabmjwxiifdfnpnqhmkasvxknv7cytu4klzcouq7323e4ifqvlhyd.onion
tesflty7y3lzxvbskfn3sltgysggrk2nlsaidnibw4k4mwe2w4663wqd.onion
tessyhjvt6txb3uu765bvb43sobswqmrfpl4xg37uetryw2ykxxcjgqd.onion
tesvthfuxverbgmvtu55xowxe5s6aloxtgvax34ycvd7hpbcd4jef3ad.onion
```
fyi, i have just reverted an unrelated commit, but i don't think it should impact imports.

**Comment by bombardinotungtung** [comment]
still same .even with vpn and dns changed.

go version go1.14.4 android/arm64

termux

**Comment by rdkr** [comment]
i'm afraid i don't understand. what is the same? what do vpn / dns have to do with the issue? you have provided no details to debug your issue.

you can reopen a new issue with more details if you would like, however if the issue is related to the android/arm64 version of go and then i'm afraid i am not familiar with this and this project only targets linux/amd64.
